repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
            "--remove-unused-variables",
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: [--skip, "__init__.py", --filter-files]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--config, "pyproject.toml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
        args: [--config, "setup.cfg"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit
      args:
      - -s
      - B101,B108,B301,B322,B403,B404,B601,B603,B607

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      args: [--config-file, "pyproject.toml"]
